spring:
  application.name: GpbBotConfigServer
  profiles.active: git
  cloud.config.server.git:
    uri: git@github.com:vnsemkin/GpbBotConfigServer.git
    search-paths: config
    default-label: trunk
server.port: 8099