# Spring
server.port: 8082

# Datasource
spring.datasource.url: jdbc:postgresql://gpb-postgres:5432/gpb

# FlyWay
spring.flyway.url: jdbc:postgresql://gpb-postgres:5432/gpb
spring.flyway.locations: classpath:db/migration