# Spring
server.port: 8082
backend.base-url: http://fake-backend:8080

# Datasource
spring.datasource.url: jdbc:postgresql://gpb-postgres:5432/gpb

# FlyWay
spring.flyway.url: jdbc:postgresql://gpb-postgres:5432/gpb
spring.flyway.locations: classpath:db/migration

# Actuator, Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    probes:
      enabled: true


